export { default as HooksPage } from './HooksPage'
export { default as PlansPage } from './PlansPage'
export { default as MemoryPage } from './MemoryPage'
export { default as SettingsPage } from './SettingsPage'
export { default as ThemesPage } from './ThemesPage'
export { default as SkillsPage } from './SkillsPage'
export { DbPage } from './DbPage'
